title: Minh Nguyen - Portfolio
description: Professional CV and Project Portfolio
url: "https://minhnq0702.github.io"

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-sitemap

# Personal Information Variables
name: "Minh Nguyen"
title_job: "Software Engineer"
email: "minhnq0702@example.com"
phone: "+1234567890"
location: "Ho Chi Minh City, Vietnam"
linkedin: "minhnq0702"
github: "minhnq0702"

# Projects Configuration
projects:
  - name: "E-commerce Platform"
    slug: "project1"
    tech: "React, Node.js, MongoDB"
    summary: "A full-stack e-commerce solution with payment integration"
  - name: "AI Chatbot"
    slug: "project2"
    tech: "Python, TensorFlow, Flask"
    summary: "Intelligent chatbot for customer service automation"
  - name: "Mobile Fitness App"
    slug: "project3"
    tech: "Flutter, Firebase"
    summary: "Cross-platform fitness tracking application"
  - name: "Data Visualization Dashboard"
    slug: "project4"
    tech: "D3.js, Vue.js, Express"
    summary: "Interactive dashboard for business analytics"
  - name: "Blockchain Wallet"
    slug: "project5"
    tech: "Solidity, Web3.js, React"
    summary: "Secure cryptocurrency wallet with transaction history"
