title: Minh Nguyen
subtitle: Personal Site
description: >-
  Personal website and portfolio of Minh Nguyen
url: "https://minhnq0702.github.io"
baseurl: ""

# Navigation
urls:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Blog
    url: /blog
  - text: Projects
    url: /projects
  - text: Contact
    url: /contact

# Author Settings
author:
  name: Minh Nguyen
  avatar: profile.jpg
  bio: Software Engineer
  email: minhnq0702@example.com
  github: minhnq0702
  linkedin: minhnq0702
  twitter: minhnq0702

# Google Analytics
google_analytics: ""

# Build settings
# Using local theme setup instead of gem-based theme
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# Pagination
paginate: 4
paginate_path: "/blog/page/:num"

# Jekyll SEO Tag
twitter:
  username: minhnq0702
  card: summary

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      author: "Minh Nguyen"
      
# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - devlopr-jekyll
